name: React Basic App and Deploy


on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version:  '20'

    - name: Installing Yarn
      uses: Borales/actions-yarn@v4
      with:
          # Yarn command
          cmd: install

    - name: Create Build
      run: yarn build
      
    - name: Install Surge
      run: npm i -g surge
      
    - name: Deploy to Surge
      run: surge ./build rev-class02-react-surge.sh --token ${{secrets.SURGE_TOKEN}}  
  